### ISSUE TITLE
Cannot build image for rock5b

### ISSUE THREAD

**Issue by nandra** [radxa/meta-rockchip#1]
Using kirkstone-radxa I'm getting:
```
/data/projects//RK3588/yocto-radxa/build/tmp/work-shared/rockchip-rk3588-rock-5b/kernel-source/drivers/net/wireless/broadcom/brcm80211/brcmutil/utils.c:11:10: fatal error: brcmu_utils.h: No such file or directory
|    11 | #include <brcmu_utils.h>
|       |          ^~~~~~~~~~~~~~~
| compilation terminated.
```

**Comment by devttebayo** [comment]
Wanted to add a +1 to this issue here - would love to get a workaround to build my image 😸

**Comment by nandra** [comment]
@devttebayo please create in your layer following bbappend (`linux-rockchip_%.bbappend`):
```
FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI:append = " \
        file://wifi.cfg \
"
```

and content of `wifi.cfg` is (put this file to subfolder called `files`:
```
CONFIG_BRCMFMAC=n
```

so structure will look like:
```
├── files
│   └── wifi.cfg
└── linux-rockchip_%.bbappend
```

Please note that with this change wifi + bluetooth will not work but compilation pass.

**Comment by devttebayo** [comment]
That works for me, I'm using ethernet for now 😄 thanks for the help!!

**Comment by RadxaStephen** [comment]
I have add one wifi.cfg to disable the driver to solve the issue.
Will fix the build error in the future.

https://github.com/radxa/meta-rockchip/commits/kirkstone-radxa
