### ISSUE TITLE
No sound from headphones and speakers

### ISSUE THREAD

**Issue by LiuFeiChen** [radxa/meta-rockchip#11]
Can't hear any sound when plugging in headphones.

**Comment by RadxaStephen** [comment]
Hi, I'm checking it now.

**Comment by LiuFeiChen** [comment]
rock 5b.

**Comment by LiuFeiChen** [comment]
How do I need to configure it to work?

**Comment by RadxaStephen** [comment]
Can you update meta-rockchip and test again? The latest commit is https://github.com/radxa/meta-rockchip/commit/f1b3a63f997c855a048fa1b9942abc85bcd396e4

**Comment by LiuFeiChen** [comment]
chromium play video without sound, the sound button is gray.

weston@rockchip-rk3588-rock-5b:/bin$ aplay -l
aplay: device_list:274: no soundcards found...
