### ISSUE TITLE
CM5 support

### ISSUE THREAD

**Issue by AaronDewes** [radxa/meta-rockchip#15]
Adding support for the CM5 and CM5 Lite would be awesome.

**Comment by prepsin** [comment]
Hi there guys. Is there any chance of getting CM5 and CM5 Lite support. These are the newest Radxa CM's and what we and i'm sure others are focused on and building now. Any help would be great in respect of this. is there any more information on it??? Thank you

**Comment by AaronDewes** [comment]
Seems to be in development: https://github.com/radxa/meta-rockchip/commit/2c820fc95b999aeec3fb7c5861280ebcad0ba2b0

Thanks @RadxaStephen!

**Comment by RadxaStephen** [comment]
Please check this README to get the code and build CM5 machine. https://github.com/radxa/yocto-manifests/blob/master/README.md
