### ISSUE TITLE
How to build single recipe?

### ISSUE THREAD

**Issue by redfast00** [radxa/meta-rockchip#2]
We'd like to build the latest chromium recipe, with the patches for hardware acceleration. I've read the wiki and the README, but was unable to figure out how to only build the chromium binary. Do you have any instructions/documentation?

**Comment by nandra** [comment]
@redfast00 you need to add meta-browser yocto layer and then you can build chromium. I would suggest to read through: https://wiki.yoctoproject.org/wiki/Building_your_own_recipes_from_first_principles

**Comment by iyangsheng** [comment]
> 我们想构建最新的铬配方，带有硬件加速补丁。我已经阅读了 wiki 和自述文件，但无法弄清楚如何只构建 chromium 二进制文件。你有任何说明/文件吗？

Is the build successful? Can you tell me about the build steps
