### ISSUE TITLE
How to flash Rock 4 SE

### ISSUE THREAD

**Issue by przemoch-dev** [radxa/meta-rockchip#5]
Hello,

project README says it was tested on `rk3399 rock 4 se board`. However, there is no instruction how to boot Rock 4 SE in maskrom mode. I'm trying to follow [this instruction for Rock 4](https://wiki.radxa.com/Rockpi4/dev/usb-install), but on `SE` there are no maskrom key. There is only some switch below USB port (on the other side of the PCB). I've been playing with this switch together with shorting `SPI1_CLK` to ground, without success.

I'm able to run the board in maskrom mode (I see it under `lsusb`) only when I completely remove SD card and eMMC module, but I would like to flash image to this emmc :)

Is there a way to flash image to eMMC or SD card on Rock 4 SE?
Thanks.

**Comment by RadxaStephen** [comment]
1.Boot the board to maskrom mode

* Remove SD card and eMMC module
* Power on ROCK 4 SE
* Insert eMMC module
* Plug Type-A to type-A cable

You will see maskrom device

```
rkdeveloptool ld
```

2.Flash the image to eMMC

```
rkdeveloptool db loader.bin
rkdeveloptool wl 0 core-image-minimal-rockchip-rk3399-rock-4se.wic
rkdeveloptool rd
```

**Comment by przemoch-dev** [comment]
Ok, it works. Thank you!
