### ISSUE TITLE
Rock 5b sees no ethernet device with default built

### ISSUE THREAD

**Issue by yrik** [radxa/meta-rockchip#7]
I've followed the steps from the readme to build and flash the image, with some changes described in [#3](https://github.com/radxa/meta-rockchip/issues/3#issuecomment-1694412827) (e.g. use rkdeveloptool instead of upgrade_tool) 

When I launch the Rock 5b have no ethernet connection. ifconfig shows only loopback device, the same for `ip link show`

**Comment by RadxaStephen** [comment]
The Ethernet dirver is built as ko. https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr4.1/arch/arm64/configs/rockchip_linux_defconfig#L602

Can you check if your build/ direcotry has r8125.ko file?

**Comment by yrik** [comment]
Thank you for the reply.

Here is the log of what I see when I run the commands you have suggested.

1. there is no `lspci` in the linux built using yocto config from this repository, so I've tried to look into `/proc/bus/pci/devices`, I don't see r8125, but I see pci port
2. There is no r8125.ko file in the system

I can also attach the image, but it's literally the result of building this repo

![Screenshot from 2023-08-27 21-19-18](https://github.com/radxa/meta-rockchip/assets/394729/7349e1eb-5fba-478a-bc5e-00c20be57bbb)

**Comment by RadxaStephen** [comment]
I find that the  r8125.ko is not added in the built image.
To solve this, I add a patch of adding kernel-modules. See https://github.com/radxa/meta-rockchip/commit/ef027f4455f705da7b4c24a63570ad9f0c512ff9.

For lspci tool, please add the following lines to your build/conf/local.conf

```
IMAGE_INSTALL:append = " \
    pciutils \
"
```

**Comment by yrik** [comment]
![image](https://github.com/radxa/meta-rockchip/assets/394729/a8059c5b-86d5-4ea1-aa6a-fb49b8674c68)

Thanks, now I can see the ethernet interface. However, looks like there is an issue with domain resolution.

**Comment by yrik** [comment]
ok, internet does work when connected directly to the router and manually set gateaway address, but not when internet is shared from the ubuntu laptop (raspberry pi works fine with laptop thought).
